name: Publish npm package

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      
      - run: yarn install --immutable
      - run: yarn build
      
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  github-release:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - run: ls -R

      - uses: ncipollo/release-action@v1
        with:
          artifacts: dist/*.js

  npm-publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org/

      - run: yarn install --immutable

      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  